"""database upgrade

Revision ID: c61f5a36051d
Revises: e795c410e48d
Create Date: 2026-09-02 00:02:34.654023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61f5a36051d'
down_revision = 'e795c410e48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_playlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('can_edit', sa.Boolean(), nullable=True),
    sa.Column('is_library', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name='fk_user_playlists_playlist_id_playlists'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_playlists_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_playlists')
    # ### end Alembic commands ###
