"""add is_library etc

Revision ID: e795c410e48d
Revises: 4c34d8cb30ef
Create Date: 2026-09-01 23:31:49.889904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e795c410e48d'
down_revision = '4c34d8cb30ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_modified_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('apple_music_id', sa.String(), nullable=True))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('apple_music_id')
        batch_op.drop_column('last_modified_date')
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###
